version: '3.8'
services:
  app:
    container_name: "proforma-notice"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - ATLAS_MONGODB=${ATLAS_MONGODB}
    ports:
      - 3000:3000